package version

// Code generated by scripts/sync-version.ts from VERSION. DO NOT EDIT.
// Release builds may still override via:
//   -ldflags="-X email-link-host/internal/version.Version=..."

var Version = "1.0.0"
