/**
 * Sync root VERSION into all applications (Next, docs, Go).
 *
 * Usage:
 *   bun run scripts/sync-version.ts           # sync current VERSION
 *   bun run scripts/sync-version.ts 1.2.3     # set VERSION then sync
 */
import { readFileSync, writeFileSync } from "node:fs";
import { join } from "node:path";

const root = join(import.meta.dirname, "..");
const versionPath = join(root, "VERSION");

const nextArg = process.argv[2]?.trim();
if (nextArg) {
  if (!/^\d+\.\d+\.\d+(-[\w.]+)?$/.test(nextArg)) {
    console.error(`Invalid semver: ${nextArg}`);
    process.exit(1);
  }
  writeFileSync(versionPath, `${nextArg}\n`, "utf8");
}

const version = readFileSync(versionPath, "utf8").trim();
if (!/^\d+\.\d+\.\d+(-[\w.]+)?$/.test(version)) {
  console.error(`Invalid VERSION file contents: ${JSON.stringify(version)}`);
  process.exit(1);
}

function setPackageVersion(pkgPath: string) {
  const raw = readFileSync(pkgPath, "utf8");
  const pkg = JSON.parse(raw) as { version?: string };
  pkg.version = version;
  writeFileSync(pkgPath, `${JSON.stringify(pkg, null, 2)}\n`, "utf8");
  console.log(`updated ${pkgPath.replace(root + "/", "")} → ${version}`);
}

setPackageVersion(join(root, "package.json"));
setPackageVersion(join(root, "docs-website/package.json"));

const goVersionPath = join(root, "internal/version/version.go");
writeFileSync(
  goVersionPath,
  `package version

// Code generated by scripts/sync-version.ts from VERSION. DO NOT EDIT.
// Release builds may still override via:
//   -ldflags="-X email-link-host/internal/version.Version=..."

var Version = "${version}"
`,
  "utf8",
);
console.log(`updated internal/version/version.go → ${version}`);

const composePath = join(root, "compose.yml");
const compose = readFileSync(composePath, "utf8").replace(
  /VERSION:\s*\$\{VERSION:-[^}]+\}/,
  `VERSION: \${VERSION:-${version}}`,
);
writeFileSync(composePath, compose, "utf8");
console.log(`updated compose.yml default VERSION → ${version}`);

console.log(`VERSION ${version}`);
